### ISSUE TITLE
Add rpmbuild to container

### ISSUE THREAD

**Issue by LStuker** [InWork/docker-ruby-golang-centos#1]
For building rpm in docker containers we should install rpmbuild.

```
yum install -y rpmbuild
```

**Comment by damoiser** [comment]
I would probably create another project for the builds (it can be inherited from this) and keep this project more "cleaned" and - for the moment - test-oriented only. 

The issues that I see mixing differents "goals" in one are: 
- the image will be bigger and bigger (and we don't need lot of features for tests-only) 
- we'll reach with an image that does everything (we don't differentiate the scope of the project), then will be more difficult to split it later (seen all dependencies already created)

**Comment by LStuker** [comment]
Agree that we should not create on giant docker image. But in this case I think the extra amount of work to create a separate docker image to just hold rpmbuild would be in my opinion a overkill.

It is just 1 mb extra.
